import { ApiKeyAuthenticationProvider, ApiKeyLocation } from "@microsoft/kiota-abstractions";
import { FetchRequestAdapter } from "@microsoft/kiota-http-fetchlibrary";
import { createLhdnClient } from "./generated/lhdnClient.js";

// Export everything from the generated models so consumers can use the types
export * from "./generated/models/index.js";

export interface LhdnClientOptions {
  apiKey: string;
  baseUrl?: string;
}

/**
 * Initializes the Lazuar LHDN API Client.
 */
export function initLhdnClient(options: LhdnClientOptions) {
  // 1. Setup the API Key Authentication Provider
  const authProvider = new ApiKeyAuthenticationProvider(
    options.apiKey,
    "Authorization",
    ApiKeyLocation.Header
  );

  // 2. Initialize the standard Fetch Request Adapter (natively includes exponential backoff retries)
  const adapter = new FetchRequestAdapter(authProvider);
  
  if (options.baseUrl) {
    adapter.baseUrl = options.baseUrl;
  }

  // 3. Return the functional client generated by Kiota v2
  return createLhdnClient(adapter);
}
