/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/lhdn/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["LhdnOperations_submitDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lhdn/documents/{internalId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LhdnOperations_getDocumentStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lhdn/documents/{internalId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["LhdnOperations_cancelDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lhdn/taxpayer/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["LhdnOperations_validateTaxpayerTin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lhdn/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LhdnOperations_listWebhooks"];
        put?: never;
        post: operations["LhdnOperations_registerWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lhdn/webhooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["LhdnOperations_deleteWebhook"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lhdn/workspaces/{id}/lhdn-certificate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["LhdnOperations_updateCertificate"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Core.IdResponse": {
            id: string;
        };
        /** RFC 7807 Standardized Error Response */
        "Core.ProblemDetails": {
            type?: string;
            title?: string;
            /** Format: int32 */
            status?: number;
            detail?: string;
            instance?: string;
        };
        "Core.StatusResponse": {
            status: string;
        };
        /** RFC 7807 Extended Validation Error Response */
        "Core.ValidationProblemDetails": {
            errors?: {
                [key: string]: string[];
            };
        } & components["schemas"]["Core.ProblemDetails"];
        "Lhdn.CancelDocumentRequestDto": {
            reason: string;
        };
        "Lhdn.LhdnAddressDto": {
            line1: string;
            line2?: string;
            line3?: string;
            city: string;
            postal_code: string;
            /** @enum {string} */
            state_code: "01" | "02" | "03" | "04" | "05" | "06" | "07" | "08" | "09" | "10" | "11" | "12" | "13" | "14" | "15" | "16" | "17";
            country_code: string;
        };
        "Lhdn.LhdnDocumentResponseDto": {
            internal_id: string;
            lhdn_uuid?: string;
            long_id?: string;
            status: string;
            qr_link?: string;
            error_message?: string;
            /** Format: date-time */
            submitted_at: string;
            /** Format: date-time */
            validated_at?: string;
        };
        "Lhdn.LhdnItemDto": {
            description: string;
            classification_code: string;
            /** Format: double */
            quantity: number;
            /** Format: double */
            unit_price: number;
            /** Format: double */
            tax_rate: number;
            /** Format: double */
            tax_amount: number;
            /** Format: double */
            subtotal: number;
            /** @enum {string} */
            tax_type_code: "01" | "02" | "03" | "04" | "05" | "06" | "E";
        };
        "Lhdn.RegisterWebhookRequestDto": {
            url: string;
            secret: string;
            events: string[];
        };
        "Lhdn.SubmitDocumentRequestDto": {
            internal_id: string;
            /** @enum {string} */
            document_type: "01" | "02" | "03" | "04" | "11" | "12" | "13" | "14";
            document_version?: string;
            /** Format: date-time */
            issue_date: string;
            original_lhdn_uuid?: string;
            adjustment_reason?: string;
            /** Format: date-time */
            billing_period_start?: string;
            /** Format: date-time */
            billing_period_end?: string;
            buyer_name: string;
            buyer_tin: string;
            /** @enum {string} */
            buyer_id_type: "BRN" | "NRIC" | "PASSPORT" | "ARMY";
            buyer_id_value: string;
            buyer_email?: string;
            buyer_phone?: string;
            buyer_address: components["schemas"]["Lhdn.LhdnAddressDto"];
            items: components["schemas"]["Lhdn.LhdnItemDto"][];
            /** Format: double */
            total_excluding_tax: number;
            /** Format: double */
            total_tax: number;
            /** Format: double */
            total_including_tax: number;
        };
        "Lhdn.UpdateLhdnCertificateRequestDto": {
            p12_base64_file: string;
            passphrase: string;
        };
        "Lhdn.ValidateTinRequestDto": {
            tin: string;
            /** @enum {string} */
            id_type: "BRN" | "NRIC" | "PASSPORT" | "ARMY";
            id_value: string;
        };
        "Lhdn.ValidateTinResponseDto": {
            is_valid: boolean;
            tin: string;
            taxpayer_name?: string;
        };
        "Lhdn.WebhookSubscriptionDto": {
            id: string;
            url: string;
            events: string[];
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    LhdnOperations_submitDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Lhdn.SubmitDocumentRequestDto"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.StatusResponse"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description Access is forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
        };
    };
    LhdnOperations_getDocumentStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                internalId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lhdn.LhdnDocumentResponseDto"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description Access is forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
        };
    };
    LhdnOperations_cancelDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                internalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Lhdn.CancelDocumentRequestDto"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.StatusResponse"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description Access is forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
        };
    };
    LhdnOperations_validateTaxpayerTin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Lhdn.ValidateTinRequestDto"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lhdn.ValidateTinResponseDto"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description Access is forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
        };
    };
    LhdnOperations_listWebhooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lhdn.WebhookSubscriptionDto"][];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description Access is forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
        };
    };
    LhdnOperations_registerWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Lhdn.RegisterWebhookRequestDto"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.IdResponse"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description Access is forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
        };
    };
    LhdnOperations_deleteWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.StatusResponse"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description Access is forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
        };
    };
    LhdnOperations_updateCertificate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Lhdn.UpdateLhdnCertificateRequestDto"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.StatusResponse"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description Access is forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Core.ProblemDetails"];
                };
            };
        };
    };
}
