<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Domain\BuildingBlocks.Domain.csproj" />
    <ProjectReference Include="..\..\..\SharedKernel\SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\..\..\packages\api-types-dotnet\Lazuar.ApiContracts.csproj" />
  </ItemGroup>
</Project>
