<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Domain\Modules.Community.Domain.csproj" />
    <ProjectReference Include="..\Contracts\Modules.Community.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Application\BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\Payments\Contracts\Modules.Payments.Contracts.csproj" />
  </ItemGroup>
</Project>
