<!-- apps/lazuar-api/Modules/Community/Application/Modules.Community.Application.csproj -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Domain\Modules.Community.Domain.csproj" />
    <ProjectReference Include="..\Contracts\Modules.Community.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Application\BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\Payments\Contracts\Modules.Payments.Contracts.csproj" />
    <ProjectReference Include="..\..\CRM\Contracts\Modules.CRM.Contracts.csproj" />
    <ProjectReference Include="..\..\Messaging\Contracts\Modules.Messaging.Contracts.csproj" />
    <ProjectReference Include="..\..\One\Contracts\Modules.One.Contracts.csproj" />
    <ProjectReference Include="..\..\Billing\Contracts\Modules.Billing.Contracts.csproj" />
  </ItemGroup>
</Project>
