<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Domain\Modules.Communications.Domain.csproj" />
    <ProjectReference Include="..\Contracts\Modules.Communications.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Application\BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\Commerce\Contracts\Modules.Commerce.Contracts.csproj" />
    <ProjectReference Include="..\..\Messaging\Contracts\Modules.Messaging.Contracts.csproj" />
    <ProjectReference Include="..\..\One\Contracts\Modules.One.Contracts.csproj" />
    <ProjectReference Include="..\..\CRM\Contracts\Modules.CRM.Contracts.csproj" />
    <ProjectReference Include="..\..\Billing\Contracts\Modules.Billing.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
