/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/checkouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Merchant creates a checkout. org_id is the One tenant id. Writer is One JWT owner/admin or a bound One `lzr_sk_`. 201 on mint; 200 on idempotent replay. */
        post: operations["Checkouts_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/checkouts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Merchant reads a checkout they are a member of. */
        get: operations["Checkouts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Process liveness for the focused Pay host. */
        get: operations["Health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/one/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Webhooks_one"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{orgId}/checkouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Member list. Cursor `limit` (default 50, max 100) and `after`. Not /v2. */
        get: operations["Checkouts_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{orgId}/gateway": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Singular requires `provider`. Missing query is 400, not the list envelope. */
        get: operations["Gateways_get"];
        /** @description BYOK keys. provider is stripe|chip|billplz|xendit|razorpay. Writer only. PUT test → 400. */
        put: operations["Gateways_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{orgId}/gateways": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Member list. processors is six rails, or seven with `test` outside Production. */
        get: operations["Gateways_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{orgId}/one-webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Webhooks_getOne"];
        /** @description Writer stores this shop's One `whsec_`. Process `Pay:OneWebhookSecret` is the one-shop fallback. */
        put: operations["Webhooks_putOne"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{orgId}/payment-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PaymentLinks_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{orgId}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Money_listPayments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{orgId}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Catalog_listProducts"];
        put?: never;
        /** @description Requires Bearer + writer. Currency other than MYR → 400. */
        post: operations["Catalog_createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{orgId}/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Member ping. ready is true when charges are not paused and (vault on file or Test is allowed). */
        get: operations["Orgs_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{orgId}/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Money_listReceipts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{orgId}/receipts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Money_getReceipt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{orgId}/refunds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Money_listRefunds"];
        put?: never;
        /** @description Writer. Reverse journal. Document series REF-, never RCPT-. Plane C refund.created after the writer. */
        post: operations["Money_createRefund"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{orgId}/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Member list. Dunning status is the row status. No Plane C subscription.* events. */
        get: operations["Money_listSubscriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{orgId}/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Webhooks_getOrg"];
        /** @description Writer stores the URL Pay POSTs after fulfill. Secret is Pay signing for the app, not Stripe, not One inbound. Lazuar HMAC (One dialect), not Standard Webhooks. */
        put: operations["Webhooks_putOrg"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{orgId}/webhooks/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Webhooks_rotateOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{orgId}/webhooks/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Webhooks_testOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pay/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Token is a payment-link or checkout public token. `slot_key` resumes a link child. */
        get: operations["PublicPayApi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pay/{token}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Wake-up only. Pay fetches the tx; the SPA cannot assert paid. */
        post: operations["PublicPayApi_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pay/{token}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Starts hosted pay. Payment-link tokens require `slot_key` (8–128) or 400.
         *     Standalone checkout tokens do not.
         */
        post: operations["PublicPayApi_start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payment-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Merchant mint door. Requires Bearer + writer. No Idempotency-Key. */
        post: operations["PaymentLinks_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{provider}/{orgId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Plane B. 200 is paid `{ok}`, replay `{duplicate}`, `{ignored}`, persisted `{failed}`, or late-pay `{refunded}` — false leaves the refund row `pending` for ops, never a fake settled refund. */
        post: operations["Webhooks_psp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Pay projection of One GET /me. Requires Bearer. Not Hub /one/auth/me. */
        get: operations["Session_whoami"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CheckoutListItem: {
            id: string;
            org_id: string;
            provider?: string;
            /** Format: decimal */
            amount: number;
            currency: string;
            status: string;
            public_token?: string;
            /** Format: date-time */
            created_at: string;
            label?: string;
        };
        CheckoutListPage: {
            items: components["schemas"]["CheckoutListItem"][];
            next_cursor?: string;
        };
        CheckoutSession: {
            id: string;
            org_id: string;
            provider?: string;
            product_id?: string;
            payment_link_id?: string;
            slot_key?: string;
            /** Format: decimal */
            amount: number;
            currency: string;
            status: string;
            public_token?: string;
            pay_url?: string;
            interval?: string;
            success_url?: string;
            cancel_url?: string;
            payer_name?: string;
            payer_email?: string;
            /** Format: date-time */
            created_at: string;
        };
        ConfirmPayRequest: {
            signature?: string;
        };
        ConfirmPayResponse: {
            ok?: boolean;
            duplicate?: boolean;
            refunded?: boolean;
            reason?: string;
        };
        /** @description stripe|chip|billplz|xendit|razorpay|solana|test. Host has no default; unknown → 400. solana requires USDC. */
        CreateCheckoutRequest: {
            org_id: string;
            provider: string;
            product_id?: string;
            /** Format: decimal */
            amount: number;
            currency?: string;
            success_url?: string;
            cancel_url?: string;
            idempotency_key?: string;
            /** @description one_off | mo | yr. Default one_off. Recurring mints an incomplete subscription row; no Plane C subscription events. */
            interval?: string;
        };
        CreatePaymentLinkRequest: {
            org_id: string;
            provider: string;
            product_id?: string;
            /** Format: decimal */
            amount: number;
            currency?: string;
            /** Format: int32 */
            max_payers?: number;
            unlimited?: boolean;
            label?: string;
        };
        CreateProductRequest: {
            name: string;
            description?: string;
            /** Format: decimal */
            amount: number;
            currency?: string;
            interval?: string;
        };
        CreateRefundRequest: {
            checkout_id: string;
            /** Format: decimal */
            amount?: number;
            idempotency_key?: string;
        };
        CreatedProduct: {
            id: string;
            org_id: string;
            name: string;
            price_id: string;
            /** Format: decimal */
            amount: number;
            currency: string;
            interval: string;
        };
        GatewayList: {
            org_id: string;
            processors: components["schemas"]["GatewayView"][];
        };
        GatewayView: {
            org_id: string;
            provider?: string;
            last4?: string;
            configured: boolean;
            capability?: string;
            public_merchant_id?: string;
            environment?: string;
            webhook_configured?: boolean;
            /** @description Server-declared settlement currency for NEW charges on this rail (RailCurrencies.Default). */
            currency: string;
        };
        HealthResponse: {
            status: string;
        };
        OneWebhookEvent: {
            type?: string;
            id?: string;
            org_id?: string;
            tenant_id?: string;
        };
        OneWebhookResult: components["schemas"]["WebhookOk"] | components["schemas"]["WebhookDuplicate"];
        OneWebhookView: {
            org_id: string;
            webhook_configured: boolean;
        };
        /** @description Member ping plus whether this shop can take money: not charges_paused, and a vault row or Test allowed. */
        OrgReadyResponse: {
            org_id: string;
            ready: boolean;
        };
        OrgWebhookCreated: {
            org_id: string;
            url: string;
            webhook_configured: boolean;
            secret_prefix?: string;
            webhook_secret: string;
        };
        OrgWebhookView: {
            org_id: string;
            url?: string;
            webhook_configured: boolean;
            secret_prefix?: string;
        };
        Payment: {
            id: string;
            org_id: string;
            checkout_id: string;
            /** Format: decimal */
            amount: number;
            currency: string;
            status: string;
            provider?: string;
            payer_name?: string;
            /** Format: date-time */
            created_at?: string;
            label?: string;
        };
        PaymentLink: {
            id: string;
            org_id: string;
            provider: string;
            /** Format: decimal */
            amount: number;
            currency: string;
            status: string;
            public_token: string;
            pay_url?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: int32 */
            max_payers?: number;
            unlimited: boolean;
            /** Format: int32 */
            paid_count: number;
            /** Format: int32 */
            taken_count: number;
            /** Format: int32 */
            remaining?: number;
            label?: string;
        };
        PaymentLinkListPage: {
            items: components["schemas"]["PaymentLink"][];
            next_cursor?: string;
        };
        PaymentListPage: {
            items: components["schemas"]["Payment"][];
            next_cursor?: string;
        };
        Product: {
            id: string;
            org_id: string;
            name: string;
            prices?: components["schemas"]["ProductPrice"][];
        };
        ProductListPage: {
            items: components["schemas"]["Product"][];
            next_cursor?: string;
        };
        ProductPrice: {
            id: string;
            /** Format: decimal */
            amount: number;
            currency: string;
            interval: string;
        };
        PspWebhookResult: components["schemas"]["WebhookOk"] | components["schemas"]["WebhookDuplicate"] | components["schemas"]["WebhookIgnored"] | components["schemas"]["WebhookFailed"] | components["schemas"]["WebhookRefunded"];
        PublicPay: {
            token: string;
            /** Format: decimal */
            amount: number;
            currency: string;
            status: string;
            payer_name?: string;
            payer_email?: string;
            email_required?: boolean;
            started?: boolean;
            mine?: boolean;
            provider?: string;
            redirect_url?: string;
            /** @description Hosted URL when the scheme is solana: (QR, not a browser redirect). redirect_url is null. */
            solana_pay_url?: string;
            /** @description Process cluster. `devnet` or `mainnet-beta`. Present when provider is solana. */
            solana_cluster?: string;
            /** Format: int32 */
            remaining?: number;
            /** Format: int32 */
            max_payers?: number;
            /** Format: int32 */
            paid_count?: number;
            /** Format: int32 */
            taken_count?: number;
        };
        /** @description BYOK. provider is stripe|chip|billplz|xendit|razorpay|solana. PUT test → 400. Solana: public_merchant_id + environment devnet|mainnet; no secret/webhook_secret. */
        PutGateway: {
            provider: string;
            secret?: string;
            webhook_secret?: string;
            public_merchant_id?: string;
            environment?: string;
            key_id?: string;
            key_secret?: string;
        };
        PutOneWebhook: {
            webhook_secret: string;
        };
        PutOrgWebhook: {
            url: string;
        };
        Receipt: {
            id: string;
            org_id: string;
            number: string;
            title?: string;
            checkout_id: string;
            /** Format: decimal */
            amount?: number;
            currency?: string;
            payer_name?: string;
            /** Format: date-time */
            created_at?: string;
            label?: string;
            status?: string;
        };
        ReceiptListPage: {
            items: components["schemas"]["Receipt"][];
            next_cursor?: string;
        };
        Refund: {
            id: string;
            org_id: string;
            checkout_id: string;
            charge_id?: string;
            /** Format: decimal */
            amount: number;
            currency: string;
            status: string;
            provider?: string;
            reason?: string;
            number?: string;
            /** Format: date-time */
            created_at: string;
        };
        RefundListPage: {
            items: components["schemas"]["Refund"][];
            next_cursor?: string;
        };
        /**
         * @description Buyer start body. `slot_key` is required for payment-link tokens (trim, length 8–128);
         *     standalone checkout tokens ignore it. Also accepted as `?slot_key=` on GET /pay/{token}.
         */
        StartPayRequest: {
            name?: string;
            email?: string;
            slot_key?: string;
        };
        StartPayResponse: {
            redirect_url?: string;
            solana_pay_url?: string;
        };
        Subscription: {
            id: string;
            org_id: string;
            checkout_id: string;
            interval: string;
            status: string;
            dunning_status?: string;
            /** Format: int32 */
            attempt_count?: number;
            /** Format: date-time */
            past_due_at?: string;
            /** Format: date-time */
            created_at: string;
        };
        SubscriptionListPage: {
            items: components["schemas"]["Subscription"][];
            next_cursor?: string;
        };
        WebhookDuplicate: {
            duplicate: boolean;
        };
        WebhookFailed: {
            failed: boolean;
        };
        WebhookIgnored: {
            ignored?: string;
        };
        WebhookOk: {
            ok: boolean;
        };
        WebhookRefunded: {
            refunded: boolean;
        };
        WhoamiResponse: {
            user_id: string;
            email?: string;
            name?: string;
            is_platform_admin: boolean;
            active_org_id?: string;
            tenants: components["schemas"]["WhoamiTenant"][];
        };
        WhoamiTenant: {
            id: string;
            slug?: string;
            name?: string;
            role?: string;
            status?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Checkouts_create: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCheckoutRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSession"];
                };
            };
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSession"];
                };
            };
        };
    };
    Checkouts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSession"];
                };
            };
        };
    };
    Health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    Webhooks_one: {
        parameters: {
            query?: never;
            header?: {
                "X-Lazuar-Signature"?: string;
                "X-Lazuar-Timestamp"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["OneWebhookEvent"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OneWebhookResult"];
                };
            };
        };
    };
    Checkouts_list: {
        parameters: {
            query?: {
                limit?: number;
                after?: string;
            };
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutListPage"];
                };
            };
        };
    };
    Gateways_get: {
        parameters: {
            query: {
                provider: string;
            };
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayView"];
                };
            };
        };
    };
    Gateways_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutGateway"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayView"];
                };
            };
        };
    };
    Gateways_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayList"];
                };
            };
        };
    };
    Webhooks_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OneWebhookView"];
                };
            };
        };
    };
    Webhooks_putOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutOneWebhook"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OneWebhookView"];
                };
            };
        };
    };
    PaymentLinks_list: {
        parameters: {
            query?: {
                limit?: number;
                after?: string;
            };
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentLinkListPage"];
                };
            };
        };
    };
    Money_listPayments: {
        parameters: {
            query?: {
                limit?: number;
                after?: string;
            };
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentListPage"];
                };
            };
        };
    };
    Catalog_listProducts: {
        parameters: {
            query?: {
                limit?: number;
                after?: string;
            };
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListPage"];
                };
            };
        };
    };
    Catalog_createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedProduct"];
                };
            };
        };
    };
    Orgs_ready: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgReadyResponse"];
                };
            };
        };
    };
    Money_listReceipts: {
        parameters: {
            query?: {
                limit?: number;
                after?: string;
            };
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptListPage"];
                };
            };
        };
    };
    Money_getReceipt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
        };
    };
    Money_listRefunds: {
        parameters: {
            query?: {
                limit?: number;
                after?: string;
            };
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefundListPage"];
                };
            };
        };
    };
    Money_createRefund: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRefundRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refund"];
                };
            };
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refund"];
                };
            };
        };
    };
    Money_listSubscriptions: {
        parameters: {
            query?: {
                limit?: number;
                after?: string;
            };
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionListPage"];
                };
            };
        };
    };
    Webhooks_getOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgWebhookView"];
                };
            };
        };
    };
    Webhooks_putOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutOrgWebhook"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgWebhookCreated"];
                };
            };
        };
    };
    Webhooks_rotateOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgWebhookCreated"];
                };
            };
        };
    };
    Webhooks_testOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookOk"];
                };
            };
        };
    };
    PublicPayApi_get: {
        parameters: {
            query?: {
                slot_key?: string;
            };
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicPay"];
                };
            };
        };
    };
    PublicPayApi_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ConfirmPayRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmPayResponse"];
                };
            };
        };
    };
    PublicPayApi_start: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StartPayRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartPayResponse"];
                };
            };
        };
    };
    PaymentLinks_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePaymentLinkRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentLink"];
                };
            };
        };
    };
    Webhooks_psp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PspWebhookResult"];
                };
            };
        };
    };
    Session_whoami: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoamiResponse"];
                };
            };
        };
    };
}
