//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace Lazuar.ApiTypes
{
    using System = global::System;

    

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class IdResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ProblemDetails
    {

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        public string? Type { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("title")]
        public string? Title { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        public int? Status { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("detail")]
        public string? Detail { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("instance")]
        public string? Instance { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class StatusResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        public string Status { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ValidationProblemDetails : ProblemDetails
    {

        [System.Text.Json.Serialization.JsonPropertyName("errors")]
        public System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>>? Errors { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CancelDocumentRequestDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("reason")]
        public string Reason { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class LhdnAddressDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("line1")]
        public string Line1 { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("line2")]
        public string? Line2 { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("line3")]
        public string? Line3 { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("city")]
        public string City { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("postal_code")]
        public string Postal_code { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("state_code")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public LhdnAddressDtoState_code State_code { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("country_code")]
        public string Country_code { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class LhdnDocumentResponseDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("internal_id")]
        public string Internal_id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("lhdn_uuid")]
        public string? Lhdn_uuid { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("long_id")]
        public string? Long_id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        public string Status { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("qr_link")]
        public string? Qr_link { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("error_message")]
        public string? Error_message { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("submitted_at")]
        public System.DateTimeOffset Submitted_at { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("validated_at")]
        public System.DateTimeOffset? Validated_at { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class LhdnItemDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("description")]
        public string Description { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("classification_code")]
        public string Classification_code { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("quantity")]
        public double Quantity { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("unit_price")]
        public double Unit_price { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("tax_rate")]
        public double Tax_rate { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("tax_amount")]
        public double Tax_amount { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("subtotal")]
        public double Subtotal { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("tax_type_code")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public LhdnItemDtoTax_type_code Tax_type_code { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class RegisterWebhookRequestDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("url")]
        public string Url { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("secret")]
        public string Secret { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("events")]
        public System.Collections.Generic.List<string> Events { get; set; } = new System.Collections.Generic.List<string>();

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SubmitDocumentRequestDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("internal_id")]
        public string Internal_id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("document_type")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public SubmitDocumentRequestDtoDocument_type Document_type { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("document_version")]
        public string? Document_version { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("issue_date")]
        public System.DateTimeOffset Issue_date { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("original_lhdn_uuid")]
        public string? Original_lhdn_uuid { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("adjustment_reason")]
        public string? Adjustment_reason { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("billing_period_start")]
        public System.DateTimeOffset? Billing_period_start { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("billing_period_end")]
        public System.DateTimeOffset? Billing_period_end { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("buyer_name")]
        public string Buyer_name { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("buyer_tin")]
        public string Buyer_tin { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("buyer_id_type")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public SubmitDocumentRequestDtoBuyer_id_type Buyer_id_type { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("buyer_id_value")]
        public string Buyer_id_value { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("buyer_email")]
        public string? Buyer_email { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("buyer_phone")]
        public string? Buyer_phone { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("buyer_address")]
        public LhdnAddressDto Buyer_address { get; set; } = new LhdnAddressDto();

        [System.Text.Json.Serialization.JsonPropertyName("items")]
        public System.Collections.Generic.List<LhdnItemDto> Items { get; set; } = new System.Collections.Generic.List<LhdnItemDto>();

        [System.Text.Json.Serialization.JsonPropertyName("total_excluding_tax")]
        public double Total_excluding_tax { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("total_tax")]
        public double Total_tax { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("total_including_tax")]
        public double Total_including_tax { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UpdateLhdnCertificateRequestDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("p12_base64_file")]
        public string P12_base64_file { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("passphrase")]
        public string Passphrase { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ValidateTinRequestDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("tin")]
        public string Tin { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("id_type")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public ValidateTinRequestDtoId_type Id_type { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("id_value")]
        public string Id_value { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ValidateTinResponseDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("is_valid")]
        public bool Is_valid { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("tin")]
        public string Tin { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("taxpayer_name")]
        public string? Taxpayer_name { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class WebhookSubscriptionDto
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("url")]
        public string Url { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("events")]
        public System.Collections.Generic.List<string> Events { get; set; } = new System.Collections.Generic.List<string>();

        [System.Text.Json.Serialization.JsonPropertyName("is_active")]
        public bool Is_active { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("created_at")]
        public System.DateTimeOffset Created_at { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum LhdnAddressDtoState_code
    {

        [System.Runtime.Serialization.EnumMember(Value = @"01")]
        _01 = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"02")]
        _02 = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"03")]
        _03 = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"04")]
        _04 = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"05")]
        _05 = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"06")]
        _06 = 5,

        [System.Runtime.Serialization.EnumMember(Value = @"07")]
        _07 = 6,

        [System.Runtime.Serialization.EnumMember(Value = @"08")]
        _08 = 7,

        [System.Runtime.Serialization.EnumMember(Value = @"09")]
        _09 = 8,

        [System.Runtime.Serialization.EnumMember(Value = @"10")]
        _10 = 9,

        [System.Runtime.Serialization.EnumMember(Value = @"11")]
        _11 = 10,

        [System.Runtime.Serialization.EnumMember(Value = @"12")]
        _12 = 11,

        [System.Runtime.Serialization.EnumMember(Value = @"13")]
        _13 = 12,

        [System.Runtime.Serialization.EnumMember(Value = @"14")]
        _14 = 13,

        [System.Runtime.Serialization.EnumMember(Value = @"15")]
        _15 = 14,

        [System.Runtime.Serialization.EnumMember(Value = @"16")]
        _16 = 15,

        [System.Runtime.Serialization.EnumMember(Value = @"17")]
        _17 = 16,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum LhdnItemDtoTax_type_code
    {

        [System.Runtime.Serialization.EnumMember(Value = @"01")]
        _01 = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"02")]
        _02 = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"03")]
        _03 = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"04")]
        _04 = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"05")]
        _05 = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"06")]
        _06 = 5,

        [System.Runtime.Serialization.EnumMember(Value = @"E")]
        E = 6,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum SubmitDocumentRequestDtoDocument_type
    {

        [System.Runtime.Serialization.EnumMember(Value = @"01")]
        _01 = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"02")]
        _02 = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"03")]
        _03 = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"04")]
        _04 = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"11")]
        _11 = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"12")]
        _12 = 5,

        [System.Runtime.Serialization.EnumMember(Value = @"13")]
        _13 = 6,

        [System.Runtime.Serialization.EnumMember(Value = @"14")]
        _14 = 7,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum SubmitDocumentRequestDtoBuyer_id_type
    {

        [System.Runtime.Serialization.EnumMember(Value = @"BRN")]
        BRN = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"NRIC")]
        NRIC = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"PASSPORT")]
        PASSPORT = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"ARMY")]
        ARMY = 3,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum ValidateTinRequestDtoId_type
    {

        [System.Runtime.Serialization.EnumMember(Value = @"BRN")]
        BRN = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"NRIC")]
        NRIC = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"PASSPORT")]
        PASSPORT = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"ARMY")]
        ARMY = 3,

    }


}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625