<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Domain\Modules.Messaging.Domain.csproj" />
    <ProjectReference Include="..\Contracts\Modules.Messaging.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Application\BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\One\Contracts\Modules.One.Contracts.csproj" />
    <ProjectReference Include="..\..\Community\Contracts\Modules.Community.Contracts.csproj" />
    <ProjectReference Include="..\..\CRM\Contracts\Modules.CRM.Contracts.csproj" />
  </ItemGroup>
</Project>
