<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Domain\Modules.Commerce.Domain.csproj" />
    <ProjectReference Include="..\Contracts\Modules.Commerce.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Application\BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\One\Contracts\Modules.One.Contracts.csproj" />
    <ProjectReference Include="..\..\CRM\Contracts\Modules.CRM.Contracts.csproj" />
    <ProjectReference Include="..\..\Payments\Contracts\Modules.Payments.Contracts.csproj" />
    <ProjectReference Include="..\..\Communications\Contracts\Modules.Communications.Contracts.csproj" />
    <ProjectReference Include="..\..\Billing\Contracts\Modules.Billing.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="MediatR" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Lazuar.ModuleTests" />
  </ItemGroup>

</Project>
